```{r}

library(reshape2)
library(ggplot2)
library(grid)
library(directlabels)
library(ellipse)
```

```{r}
cgreen <- rgb(77,175,74,maxColorValue =255)
cpurple <- rgb(152,78,163,maxColorValue =255)
cblue <- rgb(55,126,184,maxColorValue =255)
cred <- rgb(228,26,28,maxColorValue =255)
```


```{r include=FALSE}

#I will use tb_taxa that I created before melting the main taxa and its proportion by sampletype and study_group (treatment)
bm <- assignment_counts %>%
  filter(SampleID %in% s_sites$SampleID) %>%
  mutate(Assignment = fct_lump(Assignment, n=10, w=Proportion)) %>%
  # Sum in each sample
  group_by(SampleID, Assignment) %>%
  summarize(Proportion = sum(Proportion)) %>%
  ungroup() %>%
  left_join(s_sites, by="SampleID") %>%
  filter(SampleType=="Feces") #Only Oral samples will be included


bm <- subset(bm, Proportion!="")
bm <- arrange(bm, SampleID, study_group, Assignment, SampleType, Proportion)

library(plyr)
bms <- ddply(bm, .(SampleID, study_group, Assignment, SampleType, Proportion), function (x) {
  if (grepl("/", x$Proportion, fixed=T)) {
    print(x$Proportion)
    ns <- unlist(strsplit(x$Proportion, "/", fixed=T))
    print(ns)
    data.frame(
      SampleID=x$SampleID,
      study_group=x$study_group,
      TaxonLabel=x$Assignment,
      Proportion=as.numeric(ns))
  } else {
    x
  }
})
bms <- arrange(bms, SampleID, study_group, Assignment)
write.table(
  bms, file="ALL_TaxonLabel_basic.tsv",
  quote=F, sep="\t", row.names=F)
```

```{r Preparing data }

a <- read.delim("ALL_TaxonLabel_basic.tsv", check.names=F)
a <- ddply(a, .(study_group), mutate,
  Label=paste0(substr(as.character(study_group), 1, 1), as.numeric(factor(SampleID)))) 
am <- aggregate(Proportion ~ Assignment + SampleID + study_group + Label + SampleType, a, sum) 

with(am, table(Assignment, study_group)) #Counting sample number by study_group appears the assignment

s <- aggregate(study_group ~ Label + SampleID + SampleType, a, FUN=head, n=1)
s$study_group <- factor(s$study_group, levels=c("PBS", "TB"))
study_groups <- s$study_group
names(study_groups) <- as.character(s$Label)

SampleTypes <- s$SampleType

```





```{r PCA}
ac <- acast(am, Label ~ Assignment, value.var="Proportion", fill=0)

summary(manova(ac ~ study_groups[rownames(ac)]),tol=0) #Error counting

arrange(ddply(am, .(Assignment), function (x) {
  summary(aov(scale(Proportion) ~ study_group, x))[[1]][1,]
}), `Pr(>F)`)

pc <- prcomp(ac, scale.=T) #Principal Component analysis based on study_group and assignment Props (ac)

pcdf <- data.frame(Label=rownames(pc$x), PC1=pc$x[,1], PC2=pc$x[,2])
pcdf <- merge(pcdf, s, by="Label")

#PCA plot
loading_df <- as.data.frame(3 * sweep(pc$rotation, 2, pc$sdev, `*`)[,1:2])
loading_df$Assignment <- rownames(loading_df) 
loading_df <- loading_df %>%
  separate(Assignment, c("Phylum", "Taxa"), " ")
loading_df[is.na(loading_df)] <- c("Other")
biplot(prcomp(ac, scale.=T))

```



##Kyle code
```{r}
library(MASS)

ld <- lda(ac, grouping=c(study_groups, SampleTypes)[rownames(ac)])
ld
plot(ld)
#List of elements: class= LDA's prediction about treatment; posterior= matrix probability that the corresponding observation belongs to the class; x= linear discriminants
predict(ld)

ld$svd

ld_df <- do.call(data.frame, predict(ld))
ld_df$Label <- rownames(ld_df)
ld_df <- merge(ld_df, a, by="Label")
ggplot(ld_df) + 
  geom_point(aes(x=LD1, y=Proportion, color=class), binwidth=0.3) + 
  scale_color_manual(values = cols_group) +
  labs(x="Linear discriminant coefficients", y="Relative Proportion", color="study_group") +
  facet_wrap(Assignment ~ SampleType, scales="free_y") + 
  theme_boxplot() +
  theme(text = element_text(size = 14))
Sys.sleep(1)
#ggsave("LDA_scatter_oral_TB.pdf", width=11, height=6)
```

```{r}
library(vegan)
adonis(ac ~ study_groups[rownames(ac)])
```

```{r}
# Assign levels
ld_df <- ld_df %>%
  mutate(study_group = fct_relevel(study_group, study_group_levels)) %>%
  #mutate(Water = fct_relevel(Water, water_levels)) %>%
  mutate(SampleType = fct_relevel(SampleType, sample_type_levels))

ggplot(ld_df) + 
  geom_point(aes(x=Sample, y=LD1, fill=study_group, shape=SampleType), size=5) + 
  scale_fill_manual(values = cols_group) +
  scale_shape_manual(values=c(21, 24, 23)) +
  labs(y="Linear discriminant coefficients", x="SampleID", fill="", shape="") +
  facet_grid(~ SampleType, scales="free") + 
  theme_figures() +
  theme(text = element_text(size = 12), axis.text.x = element_text(angle = 90, hjust = 1, size = 8)) +
  guides(fill=guide_legend(override.aes=list(shape=21)))
Sys.sleep(1)
```

```{r}
ggplot(ld_df) + 
  geom_boxplot(aes(x=SampleType, y=LD1, fill=study_group)) + 
  scale_fill_manual(values = cols_group) +
  labs(y="Linear discriminant coefficients", x="", fill="", shape="") +
  facet_grid(~ SampleType, scales="free") + 
  theme_figures() +
  theme(text = element_text(size = 14))
Sys.sleep(1)


```




##Other way
###study_group
```{r}
library(caret)
# Split the data into training (80%) and test set (20%)
set.seed(123)
training.samples <- am$study_group %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data <- am[training.samples, ]
test.data <- am[-training.samples, ]

# Estimate preprocessing parameters
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
# Transform the data using the estimated parameters
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)

```

```{r}
# Fit the model
model <- lda(study_group~., data = train.transformed)
# Make predictions
predictions <- model %>% predict(test.transformed)
# Model accuracy
mean(predictions$class==test.transformed$study_group)

plot(model)
```

```{r}
#Predictions
predictions <- model %>% predict(test.transformed)
names(predictions)

# Predicted classes
head(predictions$class, 6)
# Predicted probabilities of class memebership.
head(predictions$posterior, 6) 
# Linear discriminants
head(predictions$x, 3) 
```
```{r}
lda.data <- cbind(train.transformed, predict(model)$x)

ggplot(lda.data) + 
  geom_point(aes(x=SampleID, y=LD1, fill=study_group, shape=SampleType), size=5) + 
  scale_fill_manual(values = cols_group) +
  scale_shape_manual(values=c(21, 24)) +
  labs(y="Linear discriminant coefficients", x="SampleID", fill="", shape="") +
  facet_grid(~ SampleType, scales="free") + 
  theme_figures() +
  theme(text = element_text(size = 12), axis.text.x = element_text(angle = 90, hjust = 1, size = 8))
Sys.sleep(1)
```





```{r}
#Model Accuracy
mean(predictions$class==test.transformed$study_group)

sum(predictions$posterior[ ,1] >=.5)
```
```{r}
lda.data2 <- lda.data %>%
  group_by(SampleType, study_group, Assignment) %>%
  dplyr::summarise(LD1 = sum(LD1)) %>% #If I don't indicate the dplyr library, it works as plyr
  ungroup()

ggplot(lda.data2, aes(reorder(Assignment, -LD1), LD1, fill = study_group)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    xlab("Taxa") +
   scale_fill_manual(values = cols_group) +
  theme_figures() +
facet_grid(~ SampleType)



```


###SampleType
```{r}
library(caret)
# Split the data into training (80%) and test set (20%)
set.seed(123)
training.samples <- am$SampleType %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data <- am[training.samples, ]
test.data <- am[-training.samples, ]

# Estimate preprocessing parameters
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
# Transform the data using the estimated parameters
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)

```

```{r}
# Fit the model
model <- lda(SampleType~., data = train.transformed)
# Make predictions
predictions <- model %>% predict(test.transformed)
# Model accuracy
mean(predictions$class==test.transformed$SampleType)

plot(model)
```

```{r}
#Predictions
predictions <- model %>% predict(test.transformed)
names(predictions)

# Predicted classes
head(predictions$class, 6)
# Predicted probabilities of class memebership.
head(predictions$posterior, 6) 
# Linear discriminants
head(predictions$x, 3) 
```

```{r}
lda.data <- cbind(train.transformed, predict(model)$x)

ggplot(lda.data) + 
  geom_point(aes(x=SampleID, y=LD1, fill=study_group, shape=SampleType), size=5) + 
  scale_fill_manual(values = cols_group) +
  scale_shape_manual(values=c(21, 24)) +
  labs(y="Linear discriminant coefficients", x="SampleID", fill="", shape="") +
  facet_grid(~ SampleType, scales="free") + 
  theme_figures() +
  theme(text = element_text(size = 12), axis.text.x = element_text(angle = 90, hjust = 1, size = 8))
Sys.sleep(1)
```





```{r}
#Model Accuracy
mean(predictions$class==test.transformed$SampleType)

sum(predictions$posterior[ ,1] >=.5)
```

```{r}
lda.data2 <- lda.data %>%
  group_by(SampleType, study_group, Assignment) %>%
  dplyr::summarise(LD1 = sum(LD1)) %>% #If I don't indicate the dplyr library, it works as plyr
  ungroup()

ggplot(lda.data2, aes(reorder(Assignment, -LD1), LD1, fill = study_group)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    xlab("Taxa") +
   scale_fill_manual(values = cols_group) +
  theme_figures() +
facet_grid(~ SampleType)



```

