To run after the main Rmd file: Body.Sites.Fig1.Rmd

```{r}
library(nlme)
tidy_lmer <- function(lmer_test) {
  mod <- summary(lmer_test)
  data.frame(term  = rownames(mod$tTable), mod$tTable, row.names=NULL)
}
```

```{r}
#Ceylan: 1. s_toTest  data frame of sample information, one sample per row. It needs to have a column  called SampleID that matches with the proportions. It also needs to have a column called otu_counts which is the number of features in a sample.
otu_counts_tb <- select(otu_counts, SampleID, Counts)

#Aurea:
s_tb <- s %>%
  left_join(read_counts, by="SampleID") %>%
  filter(Water %in% "Sucrose", study_group %in% c("PBS", "TB")) %>%
  left_join(alpha_df, by="SampleID")  %>%
  left_join(otu_counts_tb, by="SampleID")

#Ceylan: 2. counts # matrix of counts. It should have features as row names and SampleIDs as column names.
#Aurea:
counts.fc <- reshape2::acast(otu_counts, Assignment ~ SampleID , value.var='Counts')[,s_tb$SampleID]

#Ceylan: 3. rows_to_test the index of features you would like to test on. I would recommend 
#Aurea
rows_to_test <- taxa_coords[,1] %>% unlist() selecting the taxa that are generally abundant in the samples. Linear models are not accurate if there are a lot of zeros in the sample.

#Ceylan: 4. form1 # The formula you would like to test. One example is "props_logit ~ study_group"
rep_mes_form # This is the repeated measures formula. Most likely it will be something like "~1|SubjectID"
#Aurea: I don't understand this...

summaries_df <- counts.fc[rows_to_test, s_tb$SampleID] %>%
    melt() %>%
    mutate(value = value+1) %>%
    setNames(c("Taxa", "SampleID", "Abundance")) %>%
    merge(s_tb, by="SampleID") %>%
    mutate(props = Abundance / Counts) %>%
    mutate(props_logit = log(props/(1-props))) %>%
    group_by(Taxa) %>%
    do(tidy_lmer(nlme::lme(as.formula(form1), random = as.formula(rep_mes_form), data=., na.action=na.omit))) %>%
    ungroup() %>%
    filter(term != '(Intercept)') %>%
    group_by(term) %>%
    mutate(fdr = p.adjust(p.value, method="BH")) %>%
    ungroup() 


#Ceylan: Then you would use those results

summaries_df %>%
  filter(fdr < 0.05) %>%
  filter(term == "the term you want to plot") %>% ### change this to the term you want to plot
  ggplot(aes(x=Taxa, y=estimate, ymin=estimate-std.error, ymax=estimate+std.error)) +
    geom_pointrange() +
    coord_flip() +
    theme_bw() +
    theme(
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
    ) +
    labs(
      y="Estimated difference\nin taxon abundance", x=""
    )
```

