---
title: "Random Forest.Aurea: BodySite Project"
author: "Aurea Simon-Soro"
date: \today
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_scripts, echo=FALSE, message=TRUE, warning=TRUE}
#Load scripts for 16S analysis

library(qiimer)
library(pander)
library(kylemisc)
library(fossil)
library(plyr)
library(tidyverse)
library(gdata)
library(pheatmap)
library(forcats)
library(ggthemes)
library(viridis)
library (ggbeeswarm)
library(reshape2)
library(vegan)
library(ggrepel)
library(gridExtra)
library(ggpubr)
library(ggtern)
library(randomForest)
```

```{r}
# First, re-arrange samples in matrix to same order as s
rf_predictors <- taxon_props[!(rownames(taxon_props) %in% "Unassigned"),s_toPlot$SampleID] %>%
  # Log the abundance values
  apply(2, function(x) log10(x + 1e-6)) %>%
  # Flip rows and columns -- samples should be in rows
  t()

rf_response <- s_toPlot$SampleType

```

```{r}
# Re-set the random number generator
# Ensures that you get the same results each time you run randomForest
set.seed(2019)
#Training the 
rf <- randomForest(rf_predictors, rf_response, ntree = 10000, importance = T)

rf_importance <- rf$importance %>%
  as.data.frame() %>%
  mutate(Taxon = rownames(.))




```


```{r Mean decrease accuracy}
rf_importance %>%
  arrange(desc(MeanDecreaseAccuracy)) %>%
  slice(1:20) %>%
  mutate(Taxon = fct_reorder(Taxon, MeanDecreaseAccuracy)) %>%
  ggplot(aes(x=Taxon, y=MeanDecreaseAccuracy)) +
  geom_point() +
  coord_flip() +
  labs(x="", y="Mean decrease in accuracy") +
  theme_boxplot()
```

```{r Mean Decrease Gini}
rf_importance %>%
  arrange(desc(MeanDecreaseGini)) %>%
  slice(1:20) %>%
  mutate(Taxon = fct_reorder(Taxon, MeanDecreaseGini)) %>%
  ggplot(aes(x=Taxon, y=MeanDecreaseGini)) +
  geom_point() +
  coord_flip() +
  labs(x="", y="Mean decrease in Gini index") +
  theme_boxplot()
```

```{r Calculate Number of trees}
#Oob=out-of-bag error
rf_errors <- rf$err.rate

rf_errors %>%
  as_tibble() %>%
  mutate(NumTrees = 1:n()) %>%
  select(-OOB) %>%
  gather(Group, Error, -NumTrees) %>%
  ggplot(aes(y=Error, x=NumTrees, color=Group, group=Group)) +
  geom_step() +
  ggsci::scale_color_simpsons() +
  theme_bw()
```

```{r Prob Group}
#Calculate the probability the sample is assigned to a specific group
rf_group_probabilities <- rf$votes %>%
  as.data.frame() %>%
  mutate(SampleID = rownames(.))
```

```{r}
rf_group_probabilities %>%
  select(SampleID, OralProb = `Oral Swab`, FecalProb = Feces) %>%
  left_join(s, by="SampleID") %>%
  ggplot() +
  geom_point(aes(x=FecalProb, y=OralProb, color=SampleType), size=2, alpha=0.8, stroke = 2) +
  scale_x_continuous(limits=c(0, 1)) +
  scale_y_continuous(limits=c(0, 1)) +
 scale_color_manual(values = cols_Site) +
  theme_boxplot()
```

```{r}
rf_predictions <- predict(rf)
s_toPlot$PredictedSampleType <- rf_predictions

table <- table(Observed = rf_response, `RF Predicted` = rf_predictions)  %>%
 kable(caption = "Random Forest Prediction") %>%
  kableExtra::kable_styling("striped", full_width = F, bootstrap_options = "striped") 
table
```

